### ISSUE TITLE
Incorrect 'main' entry

### ISSUE THREAD

**Issue by mrbrahman** [samueldonovan1701/express-auth#13]
Hi,

This package seems very interesting - seems to do exactly what I need. I'm going to test it out.

At the outset, noticed that package.json has incorrect main entry, due to which node fails to start up.

Thanks.

**Comment by samueldonovan1701** [comment]
Fixed on v1.2.0 branch with [aff78a9](https://github.com/samueldonovan1701/express-cookie-session-auth/commit/aff78a9c04fbf3dd11f8c428b61e59d734083434)
