### ISSUE TITLE
Support for hashing of passwords?

### ISSUE THREAD

**Issue by mrbrahman** [samueldonovan1701/express-auth#14]
Hi,

I see that you have the options to provide override classes for User management. This is great, since the password will need to be hashed (say using bcrypt) in a production scenario. However, those hashing algorithms have their own compare utility (e.g. bcrypt.compare) to check for passwords. Do you have plans to support such compares?

Thanks.

**Comment by samueldonovan1701** [comment]
Hello,
see the v1.2.0 branch for an implementation where the UserManager now has a `verify` function that can be overridden.
It was added in [bcbd375](https://github.com/samueldonovan1701/express-cookie-session-auth/commit/bcbd375fec0e65d6b3a16439d7ace57604f88543)

Who knows when I'll get around to pushing the branch to main :) There'll be a number of other fixes and improvements on that branch before it's merged.
